- name: Live Illustration
  slug: live-illustration
  color: ns_yellow 
  image: Liveillustration_Nicolour.northcliffeartsparty.jpg
  alt-text: "Working on a live illustration "
  short-description: |
    Your special day, beautifully sketched
  # description: |
  #   

- name: Workshops
  slug: workshops
  color: ns_blue 
  image: Nicolour_workshop.5.JPG
  alt-text: "Helping an artists in a workshop"
  short-description: |
    Have a go at something different <br>
    and leave smiling
  # description: |
  #   

- name: Design
  slug: design
  color: ns_green 
  image: design_Nicolour.JPG
  alt-text: "Discussing my sketchbook with friends"
  short-description: |
    A peek inside my creative world
  # description: |
  #  

- name: Commissions
  slug: design
  color: ns_orange 
  image: commissions_Nicolour.jpg
  alt-text: "Illustration of a girl with her favourite toy"
  short-description: |
    Illustrations as unique as your memories
  # description: |
  #  